/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "urctpyedxqrumlpmwmtb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyY3RweWVkeHFydW1scG13bXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MTMzMzEsImV4cCI6MjA3NTQ4OTMzMX0.HbHs31S_aGGET-RVVqoPoYPVlWFz87g-NGZgixuIDqo"